# This is a basic workflow to help you get started with Actions

name: First Ci-CD pipeline


env:
  OUTPUT_PATH: ${{ github.workspace}}


on: [push]
  


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  DeployRG:
 
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # look for ps1 file
      - name: look for ps1 file
        run: |
        ls '${{ env.OUTPUT_PATH }}\gitnewtest'
      - name: provision RG in Azure
        env:
          RESOURCE_GROUP:  rg-gitewtest
          RESOURCE_GROUP_REGION: southcentralus
          
        run: >
          powershell -command "& '${{ env.OUTPUT_PATH }}\getnewtest\testcode.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}

          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

          -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}

          -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          -resourceGroupName %RESOURCE_GROUP%

          -resourceGroupNameRegion %RESOURCE_GROUP_REGION%
      
